# Generated by Django 4.1.1 on 2023-01-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_usermembership_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('pro', 'Pro'), ('free', 'Free')], default='free', max_length=30),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=100),
        ),
    ]
