# Generated by Django 4.1.1 on 2023-01-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_membership_membership_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='slug',
        ),
        migrations.AddField(
            model_name='membership',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
